-- AlterTable
ALTER TABLE "staff" ADD COLUMN     "academic_qualifications" TEXT,
ADD COLUMN     "address" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "date_of_birth" TEXT,
ADD COLUMN     "emergency_contact_name" TEXT,
ADD COLUMN     "emergency_contact_phone" TEXT,
ADD COLUMN     "emergency_contact_relationship" TEXT,
ADD COLUMN     "id_expiry_date" TEXT,
ADD COLUMN     "id_issue_date" TEXT,
ADD COLUMN     "id_number" TEXT,
ADD COLUMN     "id_type" TEXT,
ADD COLUMN     "is_transferred" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "languages_spoken" TEXT,
ADD COLUMN     "middle_name" TEXT,
ADD COLUMN     "next_of_kin_name" TEXT,
ADD COLUMN     "next_of_kin_phone" TEXT,
ADD COLUMN     "next_of_kin_relationship" TEXT,
ADD COLUMN     "photo" TEXT,
ADD COLUMN     "professional_qualifications" TEXT,
ADD COLUMN     "skills" TEXT,
ADD COLUMN     "transfer_date" TIMESTAMP(3),
ADD COLUMN     "transfer_reason" TEXT,
ADD COLUMN     "work_email" TEXT,
ADD COLUMN     "work_phone" TEXT;
