-- AlterTable
ALTER TABLE "users" ADD COLUMN     "address" TEXT,
ADD COLUMN     "biography" TEXT,
ADD COLUMN     "certifications" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "date_of_birth" TEXT,
ADD COLUMN     "department" TEXT,
ADD COLUMN     "education" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "emergency_contact_name" TEXT,
ADD COLUMN     "emergency_contact_phone_number" TEXT,
ADD COLUMN     "emergency_contact_relationship" TEXT,
ADD COLUMN     "hire_date" TIMESTAMP(3),
ADD COLUMN     "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "middle_name" TEXT,
ADD COLUMN     "phone_number" TEXT,
ADD COLUMN     "position" TEXT,
ADD COLUMN     "previous_employers" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "profile_picture" TEXT,
ADD COLUMN     "social_media_links" JSONB,
ADD COLUMN     "work_email" TEXT,
ADD COLUMN     "work_phone_number" TEXT;
